### ISSUE TITLE
Under contruction page

### ISSUE THREAD

**Issue by MatiasOS** [tandil-dev/tandil.dev#1]
**Is your feature request related to a problem? Please describe.**
We need a good lucking `under construction` page

**Describe the solution you'd like**
We need an under construction landing page. It must have a link to `blockchain.tandil.dev`

**Describe alternatives you've considered**
We can use [material UI](https://material-ui.com) and some image 
**Additional context**

**Comment by raravi** [comment]
Hi, 

Can I work on this?!

Amith

**Comment by fMercury** [comment]
Hi Amith,
if you want to cooperate !!
This is a open project that look for make blockchain technology more known.
Any help is welcomed

Fran

**Comment by raravi** [comment]
Thank You! I will submit a PR soon :)

**Comment by raravi** [comment]
Let me know if the wording in this looks okay! So that I can make the necessary changes before submitting PR!!

![Screenshot 2019-04-12 at 9 36 01 PM](https://user-images.githubusercontent.com/26003413/56061938-2b3fdc00-5d6b-11e9-95e5-936707274f4c.png)

Thank you,
Amith

**Comment by fMercury** [comment]
Oh, it looks good! 
submit the PR when you feel that it is finished.
And Thanks again for colaborate!!!
Frank

**Comment by MatiasOS** [comment]
Love it!

**Comment by raravi** [comment]
I may need help with the build error, not sure why this error cropping up! 
I'm new to next.js/typescript, but I'm used to working in React.js. 

Is Styled JS not allowed?! Inline styling will create more problems i think. 
How else do we add styles to components?

Please check the PR and the corresponding Travis CI build error in it.

![Screenshot 2019-04-13 at 12 09 40 AM](https://user-images.githubusercontent.com/26003413/56068815-84663a80-5d80-11e9-9a7e-6a5c6b1297ba.png)

Thank You,
Amith

**Comment by raravi** [comment]
I've a noob question: How do I reference this issue in my PR request?! 
I see many people do that on Github but couldn't figure out how!

Regards,
Amith

**Comment by MatiasOS** [comment]
Don't worry. We are new too! Left you a comment in pr!

**Comment by raravi** [comment]
Thank you, @MatiasOS ! I've fixed the styled-jsx error and updated the PR with this issue!

Have a good day!
Amith
